apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: team062
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30050
      protocol: TCP
  selector:
    app: postgres