apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: team062
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/loan"
  SPRING_DATASOURCE_USERNAME: "appusr"
  SPRING_DATASOURCE_PASSWORD: "mysecurepassword"
  SERVER_PORT: "30090"
  TZ: "Asia/Bangkok"


