services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: appusr
      POSTGRES_DB: loan

