apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: team062
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: team062-frontend
          imagePullPolicy: Never 
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://backend-service.team062.svc.cluster.local"
